/* GENERATED BY SCRIPTS, DO NOT EDIT DIRECTLY */
import neverExportInitializedStore, { RULE_NAME as neverExportInitializedStoreName } from './never-export-initialized-store'
import noDuplicateStoreIds, { RULE_NAME as noDuplicateStoreIdsName } from './no-duplicate-store-ids'
import noReturnGlobalProperties, { RULE_NAME as noReturnGlobalPropertiesName } from './no-return-global-properties'
import noStoreToRefsInStore, { RULE_NAME as noStoreToRefsInStoreName } from './no-store-to-refs-in-store'
import preferSingleStorePerFile, { RULE_NAME as preferSingleStorePerFileName } from './prefer-single-store-per-file'
import preferUseStoreNamingConvention, { RULE_NAME as preferUseStoreNamingConventionName } from './prefer-use-store-naming-convention'
import requireSetupStorePropertiesExport, { RULE_NAME as requireSetupStorePropertiesExportName } from './require-setup-store-properties-export'

export default {
  [neverExportInitializedStoreName]: neverExportInitializedStore,
  [noDuplicateStoreIdsName]: noDuplicateStoreIds,
  [noReturnGlobalPropertiesName]: noReturnGlobalProperties,
  [noStoreToRefsInStoreName]: noStoreToRefsInStore,
  [preferSingleStorePerFileName]: preferSingleStorePerFile,
  [preferUseStoreNamingConventionName]: preferUseStoreNamingConvention,
  [requireSetupStorePropertiesExportName]: requireSetupStorePropertiesExport,
}
